[features]
seeds = false
skip-lint = false
[programs.localnet]
dao = "EAWVST2wxrF9HFe526howaLTjgHo165dZgCRrQeDZF8M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
