[features]
seeds = false
skip-lint = false
[programs.devnet]
bookchain = "BT6d1BHTPJ6fQSXMZzvtQTjdsxbfj5pJu2o5kWEJERQs"

[registry]
url = "https://api.apr.devnet"

[provider]
cluster = "devnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
